import type { DigestItem, Source } from "./types";

export const MOCK_SOURCES: Source[] = [
  { id: "money-stuff", name: "Money Stuff", kind: "email", emailSender: "noreply@news.bloomberg.com", weight: 95 },
  { id: "apollo-slok", name: "Apollo / Sløk", kind: "email", emailSender: "torsten@apollo.com", weight: 90 },
  { id: "clouded-judgement", name: "Clouded Judgement", kind: "rss", url: "https://cloudedjudgement.substack.com/feed", weight: 85 },
  { id: "citrini", name: "Citrini Research", kind: "rss", url: "https://www.citriniresearch.com/feed", weight: 88 },
  { id: "wsj", name: "Wall Street Journal", kind: "rss", url: "https://feeds.a.dj.com/rss/RSSWorldNews.xml", weight: 80 },
];

export const MOCK_ITEMS: DigestItem[] = [
  {
    id: "mock-1",
    sourceId: "money-stuff",
    sourceName: "Money Stuff",
    title: "The private credit margin call nobody is talking about",
    url: "https://www.bloomberg.com/opinion/articles/money-stuff",
    publishedAt: new Date().toISOString(),
    cadence: "today",
    importance: 94,
    bullets: [
      "Levine walks through how mark-to-model private credit values diverge from what BDCs actually trade at, with a Blackstone vehicle as the worked example.",
      "Argues the 'no volatility' pitch for private credit is partly a measurement artifact — the underlying assets are no less risky than levered loans.",
      "Practical takeaway for L/S: BDC discounts to NAV may not mean what management's deck says they mean.",
    ],
    whyItMatters: "Sets up a potential pair trade narrative: short overvalued BDCs vs long the underlying syndicated loans.",
  },
  {
    id: "mock-2",
    sourceId: "wsj",
    sourceName: "WSJ — Markets",
    title: "Fed minutes signal divided committee on cut timing",
    url: "https://www.wsj.com/markets",
    publishedAt: new Date().toISOString(),
    cadence: "today",
    importance: 91,
    bullets: [
      "April FOMC minutes show meaningful split between members who see cuts in Q3 vs. those wanting confirmation of further disinflation.",
      "Dot plot from March now looks stale; market implied probability of a July cut has dropped to ~40% from ~65% pre-release.",
      "Rates desks repositioning: belly of the curve underperformed wings on the headline.",
    ],
    whyItMatters: "Rate-sensitive longs (REITs, small caps, unprofitable tech) likely under pressure today.",
  },
  {
    id: "mock-3",
    sourceId: "apollo-slok",
    sourceName: "Apollo / Sløk",
    title: "Chart: Consumer credit card delinquencies hit new cycle high",
    url: "https://www.apolloacademy.com/daily-chart",
    publishedAt: new Date().toISOString(),
    cadence: "today",
    importance: 86,
    bullets: [
      "90+ day card delinquencies among 18-29 year olds now exceeds 2008-2009 levels per NY Fed data.",
      "Sløk notes the divergence with prime borrowers, where delinquencies remain subdued — a K-shaped consumer story sharpening.",
      "Implication: lower-income exposed names (Dollar Tree, Capital One subprime, BNPL) may see Q2 credit guidance shift.",
    ],
  },
  {
    id: "mock-4",
    sourceId: "citrini",
    sourceName: "Citrini Research",
    title: "Power Demand basket: rebalancing after the Q1 hyperscaler capex prints",
    url: "https://www.citriniresearch.com/p/power-demand-basket-update",
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
    cadence: "today",
    importance: 82,
    bullets: [
      "Adds two new names to the power demand basket post-MSFT/META/GOOGL capex prints — both are utility-adjacent and have been laggards YTD.",
      "Trims position in a name that has run 60%+ since inclusion; says the risk/reward no longer screens.",
      "Reiterates conviction that AI capex → power demand → grid buildout is a 3-5 year theme, not a 2026 momentum trade.",
    ],
    whyItMatters: "Citrini's basket changes have been front-running broader sell-side; worth tracking for follower flow.",
  },
  {
    id: "mock-5",
    sourceId: "wsj",
    sourceName: "WSJ — Real Estate",
    title: "Office-to-residential conversions stall as construction costs hold firm",
    url: "https://www.wsj.com/real-estate",
    publishedAt: new Date().toISOString(),
    cadence: "today",
    importance: 74,
    bullets: [
      "Despite policy tailwinds in NYC and SF, fewer than 12% of announced conversions broke ground in 2025.",
      "Hard costs (mechanical, plumbing) per buildable sqft running 30-40% above pro forma underwriting.",
      "Implication: office distress thesis remains intact; conversions are not the relief valve sponsors hoped for.",
    ],
  },
  {
    id: "mock-6",
    sourceId: "clouded-judgement",
    sourceName: "Clouded Judgement",
    title: "Q1 2026 SaaS Earnings Scorecard — Week 4",
    url: "https://cloudedjudgement.substack.com/p/q1-2026-earnings-week-4",
    publishedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    cadence: "weekly",
    importance: 88,
    bullets: [
      "Ball's running tally: 67% of SaaS names have beat consensus rev so far, but median NDR has compressed another 200bps YoY.",
      "AI revenue disclosure remains uneven — MongoDB and Datadog leading on transparency; Snowflake conspicuously quiet.",
      "FCF margin expansion is the new bull case; ARR growth alone no longer earns a premium multiple in this tape.",
    ],
    whyItMatters: "Use this as your master tracker before the L/S club's Friday SaaS pitch session.",
  },
  {
    id: "mock-7",
    sourceId: "money-stuff",
    sourceName: "Money Stuff",
    title: "On corporate governance theater (long read)",
    url: "https://www.bloomberg.com/opinion/articles/money-stuff-long",
    publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    cadence: "weekly",
    importance: 70,
    bullets: [
      "Levine on why activist campaigns increasingly settle before proxy votes — and what that means for the activist fee model.",
      "Case study: three campaigns in 2025-26 that ended with board seats but no operational change.",
      "Useful framing for evaluating any activist position in your club's L/S book.",
    ],
  },
  {
    id: "mock-8",
    sourceId: "citrini",
    sourceName: "Citrini Research",
    title: "GLP-1 v3: where the second-order trades are now",
    url: "https://www.citriniresearch.com/p/glp1-v3",
    publishedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    cadence: "weekly",
    importance: 78,
    bullets: [
      "First-order GLP-1 longs are crowded and rich; Citrini rotates to second-order plays: medical device companies losing volume, snack/beverage names beaten down on weak hypothesis.",
      "Three new names added — two longs, one short — with sizing rationale included.",
      "Flags pharmacy benefit managers as the next leg of the trade if compounding regulation tightens.",
    ],
  },
];
