import type { Source } from "./types";

export const SOURCES: Source[] = [
  // ── TODAY tab ── time-sensitive news + daily writeups + daily news pod ──
  {
    id: "wsj-markets",
    name: "WSJ — Markets",
    kind: "rss",
    url: "https://feeds.content.dowjones.io/public/rss/RSSMarketsMain",
    weight: 80,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },
  {
    id: "wsj-world",
    name: "WSJ — World",
    kind: "rss",
    url: "https://feeds.content.dowjones.io/public/rss/RSSWorldNews",
    weight: 70,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },
  {
    id: "wsj-us-business",
    name: "WSJ — US Business",
    kind: "rss",
    url: "https://feeds.content.dowjones.io/public/rss/WSJcomUSBusiness",
    weight: 78,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },
  {
    id: "wsj-tech",
    name: "WSJ — Tech",
    kind: "rss",
    url: "https://feeds.content.dowjones.io/public/rss/RSSWSJD",
    weight: 75,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },
  {
    id: "wsj-opinion",
    name: "WSJ — Opinion",
    kind: "rss",
    url: "https://feeds.content.dowjones.io/public/rss/RSSOpinion",
    weight: 68,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },
  {
    id: "bloomberg-markets-rss",
    name: "Bloomberg — Markets",
    kind: "rss",
    url: "https://feeds.bloomberg.com/markets/news.rss",
    weight: 85,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
    itemsPerFeed: 15, // high-volume core feed
  },
  {
    id: "bloomberg-economics-rss",
    name: "Bloomberg — Economics",
    kind: "rss",
    url: "https://feeds.bloomberg.com/economics/news.rss",
    weight: 80,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },
  {
    id: "nyt-business-rss",
    name: "NYT — Business",
    kind: "rss",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    weight: 75,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
    itemsPerFeed: 15, // high-volume core feed
  },
  {
    id: "ft-markets-rss",
    name: "FT — Markets",
    kind: "rss",
    url: "https://www.ft.com/markets?format=rss",
    weight: 78,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },
  {
    id: "ft-companies-rss",
    name: "FT — Companies",
    kind: "rss",
    url: "https://www.ft.com/companies?format=rss",
    weight: 75,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },
  {
    id: "wsb",
    name: "Wall Street Breakfast",
    kind: "rss",
    url: "https://www.spreaker.com/show/5725002/episodes/feed",
    weight: 70,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },
  // ── EMAIL — only sources actually wired & forwarded to abhidailydigests@gmail.com ──
  {
    id: "apollo-slok",
    name: "Apollo / Sløk",
    kind: "email",
    emailSender: "agm@apollo.com",
    weight: 90,
    defaultCadence: "today",
    category: "markets",
    tab: "today",
  },

  // ── READS tab ── substack deep-dives, weekly long-form ──
  // High-score items (>=80) ALSO appear in Today.
  {
    id: "clouded-judgement",
    name: "Clouded Judgement",
    kind: "rss",
    url: "https://cloudedjudgement.substack.com/feed",
    weight: 85,
    defaultCadence: "weekly",
    category: "markets",
    tab: "reads",
  },
  {
    id: "citrini",
    name: "Citrini Research",
    kind: "rss",
    url: "https://www.citriniresearch.com/feed",
    weight: 88,
    defaultCadence: "today",
    category: "markets",
    tab: "reads",
  },
  {
    id: "irrational-analysis",
    name: "Irrational Analysis",
    kind: "rss",
    url: "https://irrationalanalysis.substack.com/feed",
    weight: 80,
    defaultCadence: "today",
    category: "markets",
    tab: "reads",
  },
  {
    id: "mbi-deepdives",
    name: "MBI Deep Dives",
    kind: "rss",
    url: "https://www.mbi-deepdives.com/feed",
    weight: 82,
    defaultCadence: "today",
    category: "markets",
    tab: "reads",
  },
  {
    // a16z New Media — feed exists but was empty as of wiring (no published items
    // and itunes:block=Yes). Kept here so when they start publishing the source
    // auto-flows into the Substacks tab without needing a code change.
    id: "a16z-newmedia",
    name: "a16z New Media",
    kind: "rss",
    url: "https://a16znewmedia.substack.com/feed",
    weight: 78,
    defaultCadence: "weekly",
    category: "markets",
    tab: "reads",
  },

  // ── BUSINESS BREAKDOWNS tab ── long-form deep-dive content ──
  {
    id: "acquired",
    name: "Acquired",
    kind: "rss",
    url: "https://feeds.transistor.fm/acquired",
    weight: 85,
    defaultCadence: "weekly",
    category: "markets",
    tab: "breakdowns",
  },
  {
    id: "business-breakdowns",
    name: "Business Breakdowns",
    kind: "rss",
    url: "https://feeds.megaphone.fm/breakdowns",
    weight: 80,
    defaultCadence: "weekly",
    category: "markets",
    tab: "breakdowns",
  },
  {
    id: "invest-like-the-best",
    name: "Invest Like the Best",
    kind: "rss",
    url: "https://feeds.megaphone.fm/investlikethebest",
    weight: 82,
    defaultCadence: "weekly",
    category: "markets",
    tab: "breakdowns",
  },
  {
    id: "all-in",
    name: "All-In",
    kind: "rss",
    url: "https://rss.libsyn.com/shows/254861/destinations/1928300.xml",
    weight: 65,
    defaultCadence: "weekly",
    category: "markets",
    tab: "breakdowns",
  },

  // ── RE tab ── commercial + residential real estate news ──
  {
    id: "bisnow",
    name: "Bisnow",
    kind: "rss",
    url: "https://www.bisnow.com/rss",
    weight: 75,
    defaultCadence: "today",
    category: "markets",
    tab: "re",
    itemsPerFeed: 20, // dedicated RE tab + Bisnow publishes ~15/day
  },
  {
    id: "therealdeal",
    name: "The Real Deal",
    kind: "rss",
    // Yoast SEO disables the site-wide /feed/, so use the national section feed.
    url: "https://therealdeal.com/national/feed/",
    weight: 75,
    defaultCadence: "today",
    category: "markets",
    tab: "re",
    itemsPerFeed: 15, // RE companion
  },

  // ── FUN tab ──
  {
    id: "bbc-football",
    name: "BBC Sport — Football",
    kind: "rss",
    url: "https://feeds.bbci.co.uk/sport/football/rss.xml",
    weight: 70,
    defaultCadence: "fun",
    category: "fun",
    tab: "fun",
    itemsPerFeed: 5, // Fun tab — 5 share-worthy items is plenty
  },
  {
    id: "guardian-football",
    name: "Guardian — Football",
    kind: "rss",
    url: "https://www.theguardian.com/football/rss",
    weight: 65,
    defaultCadence: "fun",
    category: "fun",
    tab: "fun",
    itemsPerFeed: 5,
  },
];
